openapi: 3.0.0
info:
  title: Heymarket API
  version: 1.0.0
  description: |
    API for interacting with Heymarket messaging service.
    Supports single messages, templates, and batch operations.

servers:
  - url: https://heymarket-api-dpbubhdceqb3fvge.canadaeast-01.azurewebsites.net
    description: Production server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string

paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time

  /api/messages/send:
    post:
      summary: Send a message to a phone number
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phoneNumber
                - message
              properties:
                phoneNumber:
                  type: string
                  description: Target phone number (10 digits)
                  example: "1234567890"
                message:
                  type: string
                  description: Message text to send
                  example: "Hello from the API!"
                attachments:
                  type: array
                  description: Optional array of media URLs
                  items:
                    type: string
                isPrivate:
                  type: boolean
                  description: Whether to create a private comment (memo) within the conversation
                  example: false
                author:
                  type: string
                  description: Display name for who the message was sent from
                  example: "Support Team"
      responses:
        '200':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      messageId:
                        type: string
                      status:
                        type: string
                      timestamp:
                        type: string
                        format: date-time
                      to:
                        type: string
                      text:
                        type: string

  /api/templates:
    post:
      summary: Create a message template
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  description: Template text with variables in {{variable}} format
                  example: "Hello {{name}}, your order {{orderId}} is ready"
                attachments:
                  type: array
                  description: Optional array of attachment URLs
                  items:
                    type: string
                isPrivate:
                  type: boolean
                  description: Whether messages using this template are private
                author:
                  type: string
                  description: Default author for messages using this template
      responses:
        '201':
          description: Template created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      text:
                        type: string
                      variables:
                        type: array
                        items:
                          type: string

    get:
      summary: List all templates
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Templates retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        text:
                          type: string
                        variables:
                          type: array
                          items:
                            type: string

  /api/templates/{templateId}/preview:
    post:
      summary: Preview a template with variables
      security:
        - ApiKeyAuth: []
      parameters:
        - name: templateId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                variables:
                  type: object
                  additionalProperties:
                    type: string
      responses:
        '200':
          description: Template preview generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      text:
                        type: string
                      variables:
                        type: array
                        items:
                          type: string

  /api/messages/batch:
    post:
      summary: Create a batch message operation
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - template
                - recipients
              properties:
                batchId:
                  type: string
                  description: Optional unique identifier for idempotency
                template:
                  type: object
                  oneOf:
                    - type: object
                      required:
                        - id
                      properties:
                        id:
                          type: string
                          description: ID of an existing template
                    - type: object
                      required:
                        - text
                      properties:
                        text:
                          type: string
                          description: Custom message text with variables in {{variable}} format
                        attachments:
                          type: array
                          description: Optional array of media URLs
                          items:
                            type: string
                        isPrivate:
                          type: boolean
                          description: Whether messages are private
                        author:
                          type: string
                          description: Author for the messages
                recipients:
                  type: array
                  items:
                    type: object
                    required:
                      - phoneNumber
                      - variables
                    properties:
                      phoneNumber:
                        type: string
                      variables:
                        type: object
                        additionalProperties:
                          type: string
                      overrides:
                        type: object
                        properties:
                          isPrivate:
                            type: boolean
                          author:
                            type: string
                options:
                  type: object
                  properties:
                    scheduleTime:
                      type: string
                      format: date-time
                    priority:
                      type: string
                      enum: [high, normal, low]
                    retryStrategy:
                      type: object
                      properties:
                        maxAttempts:
                          type: integer
                        backoffMinutes:
                          type: integer
      responses:
        '201':
          description: Batch created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      batchId:
                        type: string
                      status:
                        type: string
                        enum: [pending, processing, completed, failed]
                      progress:
                        type: object
                        properties:
                          total:
                            type: integer
                          pending:
                            type: integer
                          processing:
                            type: integer
                          completed:
                            type: integer
                          failed:
                            type: integer

  /api/messages/batch/{batchId}:
    get:
      summary: Get batch operation status
      security:
        - ApiKeyAuth: []
      parameters:
        - name: batchId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Batch status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                      progress:
                        type: object
                      timing:
                        type: object
                      errors:
                        type: object
                      metrics:
                        type: object
                        properties:
                          messages_per_second:
                            type: number
                          success_rate:
                            type: number
                          credits_used:
                            type: number
                      results:
                        type: array
                        items:
                          type: object
                          properties:
                            phoneNumber:
                              type: string
                            status:
                              type: string
                              enum: [success, skipped, failed]
                            reason:
                              type: string
                              enum: [duplicate_message]
                              description: Present when status is 'skipped'
                            error:
                              type: string
                              description: Present when status is 'failed'
                            errorCategory:
                              type: string
                              enum: [rate_limit, invalid_request, network_error, timeout]
                              description: Present when status is 'failed'
                            timestamp:
                              type: string
                              format: date-time

  /api/messages/batch/{batchId}/analytics:
    get:
      summary: Get batch analytics
      security:
        - ApiKeyAuth: []
      parameters:
        - name: batchId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Batch analytics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      messages_per_second:
                        type: number
                      success_rate:
                        type: number
                      completionRate:
                        type: number
                      errorBreakdown:
                        type: object
                      timing:
                        type: object

  /api/admin/message-history/{phoneNumber}:
    get:
      summary: Get message history for a phone number
      security:
        - ApiKeyAuth: []
      parameters:
        - name: phoneNumber
          in: path
          required: true
          schema:
            type: string
          description: Phone number to get history for
      responses:
        '200':
          description: Message history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      phoneNumber:
                        type: string
                      messages:
                        type: array
                        items:
                          type: object
                          properties:
                            messageHash:
                              type: string
                            timestamp:
                              type: string
                              format: date-time
                            templateId:
                              type: string
                            text:
                              type: string

  /api/admin/employee-list/lookup/{phoneNumber}:
    get:
      summary: Check if a phone number belongs to an employee
      description: |
        Employee numbers bypass duplicate prevention. Use this endpoint to check
        if a number belongs to an employee before sending messages.
      security:
        - ApiKeyAuth: []
      parameters:
        - name: phoneNumber
          in: path
          required: true
          schema:
            type: string
          description: Phone number to check
      responses:
        '200':
          description: Employee found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      phoneNumber:
                        type: string
                      name:
                        type: string
                      store:
                        type: string
                      employeeId:
                        type: string
                      lastUpdated:
                        type: string
                        format: date-time
        '404':
          description: Not an employee number
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Not found
                  message:
                    type: string
                    example: Phone number does not belong to an employee

  /api/messages/{phoneNumber}:
    get:
      summary: Get last message and customer info for a phone number
      security:
        - ApiKeyAuth: []
      parameters:
        - name: phoneNumber
          in: path
          required: true
          schema:
            type: string
          description: 10-digit phone number
      responses:
        '200':
          description: Message info retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      customerId:
                        type: string
                      lastMessage:
                        type: object
                        properties:
                          id:
                            type: string
                          text:
                            type: string
                          date:
                            type: string
                            format: date-time
                          sender:
                            type: string
                          status:
                            type: string
                          type:
                            type: string
                          channel:
                            type: string
                      messageStatus:
                        type: string
                      totalMessages:
                        type: integer
                      phoneNumber:
                        type: string
