name: Deploy to DigitalOcean
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Digital Ocean droplet via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update repository
            cd /root/heymarket
            git pull origin main
            
            # Build and deploy with Docker
            docker-compose down
            docker system prune -f
            docker-compose build --no-cache
            docker-compose up -d
            
            # Verify deployment
            docker-compose ps
            docker-compose logs --tail=50
